"""
Push model cards to the HuggingFace Hub for all trained checkpoints.

Two ways entries get built:
  - Hand-written `summary` + `details` (teacher / baseline figurative classifiers —
    one-off runs that don't come out of pipeline.py).
  - `stage` + `stage_kwargs` (tlm / clkd / calibrated) — text is generated by
    `render_stage_card()` from the same run parameters pipeline.py uses, so the
    wording stays in sync with how the checkpoint was actually produced.

`push_card_for()` is imported directly by pipeline.py and called at the end of
each stage that pushes to the Hub, so new checkpoints get a card without a
separate manual step. Run this file directly to (re)push cards for everything,
e.g. after adding a new ablation condition or if a push failed mid-job:

  python scripts/hub/push_model_cards.py
  python scripts/hub/push_model_cards.py --repo KonradBRG/xlm-mlm-abl-full-plains-cree-en-calibrated

Requires: huggingface-cli login (or HF_TOKEN env var set)
"""

from __future__ import annotations
import argparse, os, sys

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..")))

import pandas as pd
from huggingface_hub import ModelCard, ModelCardData, EvalResult, HfApi

LANGUAGE = "crk"  # Plains Cree ISO 639-3
AUTHOR   = "KonradBRG"
TEACHER  = f"{AUTHOR}/deberta-v3-base-figurative"

# Anchored to this file's location, not CWD — a relative path here would
# silently resolve to nothing (and eval_results_for() would silently return
# None) if this script is ever invoked from somewhere other than the repo
# root, which is exactly what happened once already: a card got pushed with
# its whole "Results" section missing and no error printed anywhere.
_PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
ENGLISH_RESULTS_FILE = os.path.join(_PROJECT_ROOT, "data/figurative/english_finetune_results.parquet")
FIGURATIVE_LABELS    = ["literal", "idiom", "metaphor", "simile"]


def eval_results_for(experiment_name: str, dataset_name: str = "VUA20 + MAGPIE + FLUTE") -> list[EvalResult] | None:
    """Pull this run's F1 scores from english_finetune_results.parquet (written by
    src/figurative/train.py's _save_metrics) into HF EvalResult entries, which render
    as the Hub page's "Evaluation results" widget. Returns None (never silently) if
    the run isn't in the file yet, so a missing-metrics card logs an obvious warning
    instead of quietly losing its whole Results section."""
    if not os.path.exists(ENGLISH_RESULTS_FILE):
        print(f"[cards] WARNING: {ENGLISH_RESULTS_FILE} not found — "
              f"'{experiment_name}' card will be pushed WITHOUT a Results section")
        return None
    df = pd.read_parquet(ENGLISH_RESULTS_FILE)
    row = df[df["experiment_name"] == experiment_name]
    if row.empty:
        print(f"[cards] WARNING: no row for experiment_name='{experiment_name}' in "
              f"{ENGLISH_RESULTS_FILE} — card will be pushed WITHOUT a Results section")
        return None
    row = row.iloc[0]

    def _metric(metric_type: str, metric_name: str, value) -> EvalResult | None:
        if value is None or pd.isna(value):
            return None
        return EvalResult(
            task_type="text-classification", task_name="Figurative Language Detection",
            dataset_type="vua20-magpie-flute", dataset_name=dataset_name,
            metric_type=metric_type, metric_name=metric_name, metric_value=round(float(value), 4),
        )

    results = [_metric("f1_macro", "Macro F1", row.get("macro_f1"))]
    for name in FIGURATIVE_LABELS:
        results.append(_metric(f"f1_{name}", f"{name.capitalize()} F1", row.get(f"{name}_f1")))
    return [r for r in results if r is not None]

CITATION_SECTION = """\
## Citation

If you use this model, please cite the associated thesis/paper (TBD).
"""

DATA_SECTION = """\
## Data

Training data includes:
- [Bloomfield (1934) *Plains Cree Texts*](https://bloomfield.kiyanaw.net) (scraped and sentence-aligned)
- [EdTeKLA Indigenous Languages Corpora](https://github.com/EdTeKLA/IndigenousLanguages_Corpora)
"""

STAGE_TAGS = {
    "tlm":        ["translation-language-modeling", "plains-cree", "low-resource"],
    "clkd":       ["figurative-language", "text-classification", "plains-cree", "clkd", "low-resource"],
    "calibrated": ["figurative-language", "text-classification", "plains-cree", "clkd", "low-resource", "calibrated"],
}
STAGE_PIPELINE_TAG = {
    "tlm":        "fill-mask",
    "clkd":       "text-classification",
    "calibrated": "text-classification",
}


def render_stage_card(stage: str, base_model: str, **kw) -> tuple[str, str]:
    """Return (summary, details-markdown) for a pipeline-produced checkpoint.

    kw (all optional, matching pipeline.py's CLI args for that stage):
      tlm:        epochs, learning_rate, batch_size, max_length,
                  warm_start (mono-MLM checkpoint id, if used),
                  contrastive_alpha, contrastive_temperature
      clkd:       student_base, teacher, freeze_n_layers, temperature, epochs, learning_rate
      calibrated: student_base, literal_ratio, epochs, learning_rate, ablation_note
    """
    if stage == "tlm":
        warm_note = (
            f"\nWarm-started from a monolingual Cree MLM checkpoint (`{kw['warm_start']}`) "
            f"before cross-lingual TLM fine-tuning." if kw.get("warm_start") else ""
        )
        alpha = kw.get("contrastive_alpha") or 0.0
        contrastive_note = (
            f"\nTrained jointly with an InfoNCE alignment loss (alpha={alpha}, "
            f"temperature={kw.get('contrastive_temperature', 0.05)}) that explicitly pulls "
            f"Cree and English sentence representations together." if alpha else ""
        )
        summary = (
            f"{base_model} fine-tuned with the Translation Language Modeling (TLM) objective "
            f"on a Plains Cree–English parallel corpus."
        )
        details = f"""\
## Training

Fine-tuned using the TLM objective introduced in [Lample & Conneau (2019)](https://arxiv.org/abs/1901.07291).
Cree–English sentence pairs are concatenated and masked jointly, encouraging the model to use cross-lingual context when predicting masked tokens.{warm_note}{contrastive_note}

**Training data:** Bloomfield (1934) Plains Cree texts (scraped and sentence-aligned) + EdTeKLA parallel corpus (~9,000 sentence pairs total)
**Epochs:** {kw.get('epochs', 15)} | **Batch size:** {kw.get('batch_size', 16)} | **Max length:** {kw.get('max_length', 256)}
**Hardware:** 1× NVIDIA A100 40 GB

## Intended use

This checkpoint serves as the student encoder foundation for Cross-Lingual Knowledge Distillation (CLKD) of figurative language classifiers into Plains Cree.
"""
        return summary, details

    if stage == "clkd":
        teacher     = kw.get("teacher", TEACHER)
        student     = kw.get("student_base", base_model)
        freeze      = kw.get("freeze_n_layers", 0)
        freeze_note = (
            f"Layers 0–{freeze - 1} frozen to preserve cross-lingual alignment from TLM; "
            f"remaining layers + classification head trained."
            if freeze else "All layers trainable."
        )
        warm_note = "" if kw.get("tlm_warmup", student != base_model) else " (no TLM warmup)"
        summary = (
            f"{base_model} adapted for Plains Cree figurative language detection via "
            f"Cross-Lingual Knowledge Distillation (CLKD){warm_note}."
        )
        details = f"""\
## Method

Inspired by [Cross-Lingual Knowledge Distillation (ACL 2023)](https://aclanthology.org/2023.findings-acl.885/).

**CLKD pipeline:**
1. Teacher: `{teacher}` (frozen, English)
2. Student base: `{student}`
3. {freeze_note}

The teacher predicts soft label distributions on English translations of Plains Cree sentences.
The student is trained to match these distributions on the Cree side via KL divergence.

**Training data:** ~9,000 Cree–English parallel sentence pairs
**Temperature:** {kw.get('temperature', 2.0)} | **Epochs:** {kw.get('epochs', 10)} | **Hardware:** 1× NVIDIA A100 40 GB

**Labels:** `literal` (0), `idiom` (1), `metaphor` (2), `simile` (3)
"""
        return summary, details

    if stage == "calibrated":
        student    = kw.get("student_base", base_model)
        abl_note   = f"\n**Ablation condition:** {kw['ablation_note']}\n" if kw.get("ablation_note") else ""
        summary = (
            f"{base_model} calibrated on DeepSeek-annotated Bloomfield Plains Cree sentences "
            f"for figurative language detection."
        )
        details = f"""\
## Training

Low-LR calibration of a CLKD checkpoint on gold/silver Bloomfield validation data, held out and \
evaluated against the 219 footnote-verified gold sentences.
{abl_note}
**Base checkpoint:** `{student}`
**Literal : figurative ratio:** {kw.get('literal_ratio', 3)}:1 | **Epochs:** {kw.get('epochs', 10)} | **Learning rate:** {kw.get('learning_rate', 5e-6)}
**Hardware:** 1× NVIDIA A100 40 GB

**Labels:** `literal` (0), `idiom` (1), `metaphor` (2), `simile` (3)

## Intended use

Final deployed checkpoint for figurative language detection in Plains Cree.
"""
        return summary, details

    raise ValueError(f"No card template for stage '{stage}'")


MODELS = [

    # ── TLM checkpoints — legacy (predate pipeline.py's short model-id naming) ──
    dict(
        repo_id      = f"{AUTHOR}/xlm-mlm-100-1280-plains-cree-en-tlm",
        base_model   = "FacebookAI/xlm-mlm-100-1280",
        stage        = "tlm",
        stage_kwargs = dict(epochs=15),
    ),
    dict(
        repo_id      = f"{AUTHOR}/glot500-base-plains-cree-en-tlm",
        base_model   = "cis-lmu/glot500-base",
        stage        = "tlm",
        stage_kwargs = dict(epochs=15),
    ),
    dict(
        repo_id      = f"{AUTHOR}/xlm-v-base-plains-cree-en-tlm",
        base_model   = "facebook/xlm-v-base",
        stage        = "tlm",
        stage_kwargs = dict(epochs=15, max_length=128),
    ),

    # ── TLM checkpoints — base pipeline (pipeline.py --model-id xlm-mlm/xlm-v) ──
    dict(
        repo_id      = f"{AUTHOR}/xlm-mlm-plains-cree-en-tlm",
        base_model   = "FacebookAI/xlm-mlm-100-1280",
        stage        = "tlm",
        stage_kwargs = dict(epochs=15),
    ),
    dict(
        repo_id      = f"{AUTHOR}/xlm-v-plains-cree-en-tlm",
        base_model   = "facebook/xlm-v-base",
        stage        = "tlm",
        stage_kwargs = dict(epochs=15, max_length=128),
    ),

    # ── Figurative classifiers (English teacher / baselines) ──────────────────
    dict(
        repo_id         = f"{AUTHOR}/deberta-v3-base-figurative",
        base_model      = "microsoft/deberta-v3-base",
        tags            = ["figurative-language", "text-classification", "english"],
        task            = "text-classification",
        language        = "en",
        experiment_name = "deberta_figurative",  # key into english_finetune_results.parquet
        summary    = "DeBERTa-v3-base fine-tuned on VUA20 + MAGPIE + FLUTE for 4-class figurative language detection (literal / idiom / metaphor / simile).",
        details    = """\
## Training

Fine-tuned on a combination of:
- **VUA20** — VU Amsterdam Metaphor Corpus (metaphor)
- **MAGPIE** — idiom dataset
- **FLUTE** — figurative language understanding

**Labels:** `literal` (0), `idiom` (1), `metaphor` (2), `simile` (3)
**Epochs:** up to 20 (early stopping, patience=2) | **Hardware:** 1× NVIDIA A100 40 GB

## Intended use

Frozen English teacher in the CLKD pipeline for Plains Cree figurative language detection.
The teacher produces soft-label distributions on English translations; these are distilled into a student encoder operating on Cree text.
""",
    ),

    dict(
        repo_id    = f"{AUTHOR}/xlm-r-plains-cree-en-tlm-figurative",
        base_model = "xlm-roberta-base",
        tags       = ["figurative-language", "text-classification", "plains-cree", "low-resource"],
        task       = "text-classification",
        summary    = "XLM-R-base fine-tuned for 4-class figurative language detection, using a TLM-adapted encoder for Plains Cree.",
        details    = """\
## Training

Encoder: XLM-RoBERTa-base with TLM fine-tuning on Plains Cree–English pairs.
Classifier head trained on VUA20 + MAGPIE + FLUTE (English only).

**Labels:** `literal`, `idiom`, `metaphor`, `simile`
**Epochs:** 10 | **Hardware:** 1× NVIDIA A100 40 GB
""",
    ),

    dict(
        repo_id    = f"{AUTHOR}/xlm-r-large-plains-cree-en-tlm-figurative",
        base_model = "xlm-roberta-large",
        tags       = ["figurative-language", "text-classification", "plains-cree", "low-resource"],
        task       = "text-classification",
        summary    = "XLM-R-large fine-tuned for 4-class figurative language detection, using a TLM-adapted encoder for Plains Cree.",
        details    = """\
## Training

Encoder: XLM-RoBERTa-large with TLM fine-tuning on Plains Cree–English pairs.
Classifier head trained on VUA20 + MAGPIE + FLUTE (English only).

**Labels:** `literal`, `idiom`, `metaphor`, `simile`
**Epochs:** 10 | **Hardware:** 1× NVIDIA A100 40 GB
""",
    ),

    dict(
        repo_id    = f"{AUTHOR}/xlm-mlm-100-1280-plains-cree-en-tlm-figurative",
        base_model = "FacebookAI/xlm-mlm-100-1280",
        tags       = ["figurative-language", "text-classification", "plains-cree", "low-resource"],
        task       = "text-classification",
        summary    = "XLM-MLM-100-1280 fine-tuned for 4-class figurative language detection, using a TLM-adapted encoder for Plains Cree.",
        details    = """\
## Training

Encoder: XLM-MLM-100-1280 with TLM fine-tuning on Plains Cree–English pairs.
Classifier head trained on VUA20 + MAGPIE + FLUTE (English only).

**Labels:** `literal`, `idiom`, `metaphor`, `simile`
**Epochs:** 10 | **Hardware:** 1× NVIDIA A100 40 GB
""",
    ),

    # ── CLKD models (legacy hand-run naming, predates pipeline.py) ─────────────
    dict(
        repo_id      = f"{AUTHOR}/xlm-mlm-100-1280-plains-cree-en-clkd-frozen12",
        base_model   = "FacebookAI/xlm-mlm-100-1280",
        stage        = "clkd",
        stage_kwargs = dict(student_base=f"{AUTHOR}/xlm-mlm-100-1280-plains-cree-en-tlm", freeze_n_layers=12),
    ),
    dict(
        repo_id      = f"{AUTHOR}/xlm-mlm-100-1280-plains-cree-en-clkd-full",
        base_model   = "FacebookAI/xlm-mlm-100-1280",
        stage        = "clkd",
        stage_kwargs = dict(student_base=f"{AUTHOR}/xlm-mlm-100-1280-plains-cree-en-tlm"),
    ),
    dict(
        repo_id      = f"{AUTHOR}/glot500-base-plains-cree-en-clkd-direct",
        base_model   = "cis-lmu/glot500-base",
        stage        = "clkd",
        stage_kwargs = dict(student_base="cis-lmu/glot500-base", tlm_warmup=False),
    ),
    dict(
        repo_id      = f"{AUTHOR}/glot500-base-plains-cree-en-clkd-tlm",
        base_model   = "cis-lmu/glot500-base",
        stage        = "clkd",
        stage_kwargs = dict(student_base=f"{AUTHOR}/glot500-base-plains-cree-en-tlm"),
    ),
    dict(
        repo_id      = f"{AUTHOR}/xlm-v-base-plains-cree-en-clkd-direct",
        base_model   = "facebook/xlm-v-base",
        stage        = "clkd",
        stage_kwargs = dict(student_base="facebook/xlm-v-base", tlm_warmup=False),
    ),
    dict(
        repo_id      = f"{AUTHOR}/xlm-v-base-plains-cree-en-clkd-tlm",
        base_model   = "facebook/xlm-v-base",
        stage        = "clkd",
        stage_kwargs = dict(student_base=f"{AUTHOR}/xlm-v-base-plains-cree-en-tlm"),
    ),

    # ── CLKD models — base pipeline (pipeline.py --model-id xlm-mlm/xlm-v) ──────
    dict(
        repo_id      = f"{AUTHOR}/xlm-mlm-plains-cree-en-clkd",
        base_model   = "FacebookAI/xlm-mlm-100-1280",
        stage        = "clkd",
        stage_kwargs = dict(student_base=f"{AUTHOR}/xlm-mlm-plains-cree-en-tlm"),
    ),
    dict(
        repo_id      = f"{AUTHOR}/xlm-v-plains-cree-en-clkd",
        base_model   = "facebook/xlm-v-base",
        stage        = "clkd",
        stage_kwargs = dict(student_base=f"{AUTHOR}/xlm-v-plains-cree-en-tlm"),
    ),

    # ── Calibrated models — base pipeline (pipeline.py, --model-id xlm-mlm/glot500/xlm-v) ──
    dict(
        repo_id      = f"{AUTHOR}/xlm-mlm-plains-cree-en-calibrated",
        base_model   = "FacebookAI/xlm-mlm-100-1280",
        stage        = "calibrated",
        stage_kwargs = dict(student_base=f"{AUTHOR}/xlm-mlm-plains-cree-en-clkd"),
    ),
    dict(
        repo_id      = f"{AUTHOR}/glot500-plains-cree-en-calibrated",
        base_model   = "cis-lmu/glot500-base",
        stage        = "calibrated",
        stage_kwargs = dict(student_base=f"{AUTHOR}/glot500-plains-cree-en-clkd"),
    ),
    dict(
        repo_id      = f"{AUTHOR}/xlm-v-plains-cree-en-calibrated",
        base_model   = "facebook/xlm-v-base",
        stage        = "calibrated",
        stage_kwargs = dict(student_base=f"{AUTHOR}/xlm-v-plains-cree-en-clkd"),
    ),

    # ── Calibrated models — ablation study (jobs/ablation.sh, base model: xlm-mlm-100-1280) ──
    dict(
        repo_id      = f"{AUTHOR}/xlm-mlm-abl-full-plains-cree-en-calibrated",
        base_model   = "FacebookAI/xlm-mlm-100-1280",
        stage        = "calibrated",
        stage_kwargs = dict(
            student_base   = f"{AUTHOR}/xlm-mlm-plains-cree-en-clkd",
            ablation_note  = "full pipeline — TLM → CLKD → Calibrate",
            epochs=15,
        ),
    ),
    dict(
        repo_id      = f"{AUTHOR}/xlm-mlm-abl-no-tlm-plains-cree-en-calibrated",
        base_model   = "FacebookAI/xlm-mlm-100-1280",
        stage        = "calibrated",
        stage_kwargs = dict(
            student_base   = "FacebookAI/xlm-mlm-100-1280",
            ablation_note  = "no TLM warmup — base model → CLKD → Calibrate",
            epochs=15,
        ),
    ),
    dict(
        repo_id      = f"{AUTHOR}/xlm-mlm-abl-no-clkd-plains-cree-en-calibrated",
        base_model   = "FacebookAI/xlm-mlm-100-1280",
        stage        = "calibrated",
        stage_kwargs = dict(
            student_base   = f"{AUTHOR}/xlm-mlm-plains-cree-en-tlm",
            ablation_note  = "no CLKD — TLM checkpoint → Calibrate directly",
            epochs=15,
        ),
    ),
    dict(
        repo_id      = f"{AUTHOR}/xlm-mlm-abl-neither-plains-cree-en-calibrated",
        base_model   = "FacebookAI/xlm-mlm-100-1280",
        stage        = "calibrated",
        stage_kwargs = dict(
            student_base   = "FacebookAI/xlm-mlm-100-1280",
            ablation_note  = "neither TLM nor CLKD — base model → Calibrate directly",
            epochs=15,
        ),
    ),
    dict(
        repo_id      = f"{AUTHOR}/xlm-mlm-abl-mono-mlm-plains-cree-en-calibrated",
        base_model   = "FacebookAI/xlm-mlm-100-1280",
        stage        = "calibrated",
        stage_kwargs = dict(
            student_base   = f"{AUTHOR}/xlm-mlm-abl-mono-mlm-plains-cree-en-clkd",
            ablation_note  = "Cree-only MLM warmup → TLM → CLKD → Calibrate",
            epochs=15,
        ),
    ),
    dict(
        repo_id      = f"{AUTHOR}/xlm-mlm-abl-tlm-contrastive-plains-cree-en-calibrated",
        base_model   = "FacebookAI/xlm-mlm-100-1280",
        stage        = "calibrated",
        stage_kwargs = dict(
            student_base   = f"{AUTHOR}/xlm-mlm-abl-tlm-contrastive-plains-cree-en-clkd",
            ablation_note  = "TLM + InfoNCE alignment (alpha=0.1) → CLKD → Calibrate",
            epochs=15,
        ),
    ),
]


def make_card(m: dict) -> ModelCard:
    language = m.get("language", LANGUAGE)
    stage    = m.get("stage")
    tags     = m.get("tags") or STAGE_TAGS.get(stage, [])
    task     = m.get("task") or STAGE_PIPELINE_TAG.get(stage, "text-classification")
    repo_name = m["repo_id"].split("/")[-1]

    eval_results = eval_results_for(m["experiment_name"]) if m.get("experiment_name") else None

    card_data = ModelCardData(
        language      = language if isinstance(language, list) else [language],
        license       = "cc-by-4.0",
        base_model    = m["base_model"],
        tags          = tags,
        pipeline_tag  = task,
        eval_results  = eval_results,
        model_name    = repo_name if eval_results else None,
    )

    if "summary" in m and "details" in m:
        summary, details = m["summary"], m["details"]
    else:
        summary, details = render_stage_card(stage, m["base_model"], **m.get("stage_kwargs", {}))

    results_section = ""
    if eval_results:
        rows = "\n".join(f"| {r.metric_name} | {r.metric_value} |" for r in eval_results)
        results_section = f"""
## Results

Evaluated on a held-out split of {eval_results[0].dataset_name}.

| Metric | Value |
|---|---|
{rows}
"""

    content = f"""\
---
{ card_data.to_yaml() }
---

# { repo_name }

{ summary }

{ details }
{ results_section }
{ CITATION_SECTION }

{ DATA_SECTION }
"""
    return ModelCard(content)


def push_card_for(repo_id: str, stage: str, base_model: str, **stage_kwargs) -> None:
    """Called by pipeline.py right after it pushes a checkpoint, so cards stay
    current without a manual step. Never raises — a failure here shouldn't fail
    an otherwise-successful job."""
    api = HfApi()
    try:
        api.repo_info(repo_id=repo_id, repo_type="model")
        card = make_card(dict(repo_id=repo_id, base_model=base_model, stage=stage, stage_kwargs=stage_kwargs))
        card.push_to_hub(repo_id)
        print(f"[hub] card pushed → {repo_id}")
    except Exception as exc:
        print(f"[hub] card push failed for {repo_id} — {exc}")


if __name__ == "__main__":
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--repo", default=None, help="Only push the card for this repo_id (default: all)")
    args = p.parse_args()

    api = HfApi()
    models = MODELS if args.repo is None else [m for m in MODELS if m["repo_id"] == args.repo]
    if not models:
        sys.exit(f"No entry for repo '{args.repo}' in MODELS")

    for m in models:
        repo = m["repo_id"]
        try:
            api.repo_info(repo_id=repo, repo_type="model")
            card = make_card(m)
            card.push_to_hub(repo)
            print(f"✓  {repo}")
        except Exception as exc:
            print(f"✗  {repo}  — {exc}")
